defmodule ExAch.File.HeaderTest do
  use ExUnit.Case

  alias ExAch.File.Header

  alias ExAch.File.Header.Fields.{
    ImmediateDestination,
    ImmediateOrigin,
    FileCreationDate,
    ReferenceCode,
    FileIdModifier,
    RecordTypeCode,
    PriorityCode,
    FileCreationTime,
    RecordSize,
    BlockingFactor,
    FormatCode,
    ImmediateDestinationName,
    ImmediateOriginName
  }

  describe "creating file header" do
    test "file header created successfully" do
      {:ok, immediate_destination} = ImmediateDestination.new("b071000505")
      {:ok, immediate_origin} = ImmediateOrigin.new(1234567890)
      {:ok, creation_date} = FileCreationDate.new(~D[2000-01-01])
      {:ok, reference_code} = ReferenceCode.new("refcode")
      {:ok, file_id_modifier} = FileIdModifier.new("1")
      {:ok, file_creation_time} = FileCreationTime.new(~T[23:00:00])
      {:ok, immediate_destination_name} = ImmediateDestinationName.new("LaSalle Bank")
      {:ok, immediate_origin_name} = ImmediateOriginName.new("Hollar Inc")

      {:ok, file_header} =
        Header.new(
          immediate_destination,
          immediate_origin,
          creation_date,
          file_id_modifier,
          file_creation_time: file_creation_time,
          immediate_destination_name: immediate_destination_name,
          immediate_origin_name: immediate_origin_name,
          reference_code: reference_code
        )

      # Mandatory fields required to be passed by user
      assert file_header.immediate_destination == immediate_destination
      assert file_header.immediate_origin == immediate_origin
      assert file_header.file_creation_date == creation_date
      assert file_header.file_id_modifier == file_id_modifier

      # Mandatory fields generated by library
      assert file_header.record_type_code == %RecordTypeCode{content: 1}
      assert file_header.priority_code == %PriorityCode{content: "01"}
      assert file_header.record_size == %RecordSize{content: "094"}
      assert file_header.blocking_factor == %BlockingFactor{content: 10}
      assert file_header.format_code == %FormatCode{content: 1}

      # Optional fields passed by user
      assert file_header.file_creation_time == %FileCreationTime{content: ~T[23:00:00]}

      assert file_header.immediate_destination_name == %ImmediateDestinationName{
               content: "LaSalle Bank"
             }

      assert file_header.reference_code == reference_code
      assert file_header.immediate_origin_name == %ImmediateOriginName{content: "Hollar Inc"}
    end
  end
end
